### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by mbeps** [ixahmedxi/noodle#10]
# Relation
R(subject_ID, subject_name, user_ID, user_name, user_surname, user_email, user_role, module_ID, module_name, module_code, module_year, module_term, module_group, module_timetable, task_ID, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, subtask_ID,subtask_name, subtask_completion)

# Functional Dependencies
FD = {
	subject_ID → subject_name,
	user_ID → user_name, user_surname, user_email, user_role, 
	module_ID → module_name, module_code, subject_ID,
	module_ID, module_year, module_term, module_group → module_timetable,
	task_ID → task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, module_ID, module_year, module_term, module_group, 
	subtask_ID → subtask_name, subtask_completion, task_ID,
}
* Because each module can take place in multiple years, in multiple terms and can potentially have different student groups, each timetable is unique to these 3 attributes. 

# Normalization
## Closures

- (subject_ID) = {subject_ID, subject_name}
- (user_ID) = {user_ID, user_name, user_surname, user_email, user_role}
- (module_ID) = {module_ID, module_name, module_code, subject_ID, subject_name}
- (module_ID, module_year, module_term) = {module_ID, module_name, module_code, subject_ID, subject_name, module_year, module_term, module_timetable}
- (task_ID) = {task_ID, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, module_ID, module_name, module_code, module_year, module_term, module_group, module_timetable, subject_ID, subject_name}
- (subtask_ID) = {subtask_ID, subtask_name, subtask_completion, task_ID, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, module_ID, module_name, module_code, module_year, module_term, module_group, module_timetable, subject_ID, subject_name}

## Key
((user_ID) + (subtask_ID)):

(user_ID, module_ID, module_year, module_term, subtask_ID) = {user_ID, user_name, user_surname, user_email, user_role, subtask_ID, subtask_name, subtask_completion, task_ID, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, module_ID, module_name, module_code, module_year, module_term, module_timetable, subject_ID, subject_name}

## Second Normal Form (2NF)
> Every non-primary-key attribute is fully functionally dependent on the primary key.

R(**user_ID**, user_name, user_surname, user_email, user_role, **subtask_ID**, subtask_name, subtask_completion, task_ID, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, module_ID, module_name, module_code, module_year, module_term, module_timetable, subject_ID, subject_name)
* `user_ID` → `user_name`, `user_surname`, `user_email`, `user_role` Partial Functional Dependency
* `subtask_ID` → `subtask_name`, `subtask_completion`, `task_ID`, `task_name`, `task_description`, `task_deadline`, `task_date_created`, `task_type`, `task_importance`, `task_completion`, `module_ID`, `module_name`, `module_code`, `module_year`, `module_term`, `module_timetable`, `subject_ID`, `subject_name` Partial Functional Dependency

R(user_ID, subtask_ID)
R1(**user_ID**, user_name, user_surname, user_email, user_role)
R2(**subtask_ID**, subtask_name, subtask_completion, *task_ID*, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, module_name, module_code, *module_year*, *module_term*, *module_group*, module_timetable, *subject_ID*, subject_name)

### Relations

- R(user_ID, subtask_ID)
- R1(**user_ID**, user_name, user_surname, user_email, user_role)
- R2(**subtask_ID**, subtask_name, subtask_completion, *task_ID*, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, module_name, module_code, *module_year*, *module_term*, *module_group*, module_timetable, *subject_ID*, subject_name)

## Third Normal Form (3NF)
> There is no transitive dependency for non-prime attributes. 

R(**subtask_ID**, subtask_name, subtask_completion, *task_ID*, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, module_name, module_code, *module_year*, *module_term*, *module_group*, module_timetable, *subject_ID*, subject_name)
* `subtask_ID` → `task_ID` → `task_name`, `task_description`, `task_deadline`, `task_date_created`, `task_type`, `task_importance`, `task_completion`, *`module_ID`*, *`module_year`*, *`module_term`*, *``module_group``*, *`subject_ID`*
R(**subtask_ID**, subtask_name, subtask_completion, *task_ID*)
R1(**task_ID**, task_ID*, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, module_name, module_code, *module_year*, *module_term*, *module_group*, module_timetable, *subject_ID*, subject_name)

R(**task_ID**, task_ID*, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, module_name, module_code, *module_year*, *module_term*, *module_group*, module_timetable, *subject_ID*, subject_name)
* `task_ID` → `module_ID`, `module_year`, `module_term`, `module_group` → `module_name`, `module_code`, `module_timetable`, *`module_year`*, *`module_term`*, *`module_group`*, *`subject_ID`*
R(**task_ID**, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, *module_year*, *module_term*, *module_group*)
R1(**module_ID**, **module_year**, **module_term**, **module_group**, module_name, module_code, *subject_ID*, subject_name)

R1(**module_ID**, **module_year**, **module_term**, **module_group**, module_name, module_code, *subject_ID*, subject_name)
* `module_ID`, `module_year`, `module_term`, `module_group` → `module_name`, `module_code`, `module_timetable`, *`subject_ID`*, `subject_name` Full Functional Dependency
* `module_ID` → `module_name`, `module_code`, *`subject_ID`*, *`subject_name`* Partial Functional Dependency
R(**module_ID**, **module_year**, **module_term**, **module_group**, module_timetable)
R1(**module_ID**, module_name, module_code, *subject_ID*, subject_name)

R(**module_ID**, module_name, module_code, *subject_ID*, subject_name)
* `module_ID` → `subject_ID` → `subject_name`
R(**module_ID**, module_name, module_code, *subject_ID*)
R1(**subject_ID**, subject_name)

### Relations

- R(**user_ID**, user_name, user_surname, user_email, user_role)
- R(**subject_ID**, subject_name)
- R(**module_ID**, module_name, module_code, *subject_ID*)
- R(**module_ID**, **module_year**, **module_term**, **module_group**, module_timetable)
- R(**task_ID**, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, *module_year*, *module_term*, *module_group*)
- R(**subtask_ID**, subtask_name, subtask_completion, *task_ID*)

## Boyce Codd Normal Form (BCNF)
> For every functional dependency X → Y, X must the super key of that relation.

R1(**user_ID**, user_name, user_surname, user_email, user_role)
R2(**subject_ID**, subject_name)
R3(**module_ID**, module_name, module_code, *subject_ID*)
R4(**module_ID**, **module_year**, **module_term**, module_timetable)
R5(**task_ID**, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, *module_year*, *module_term*, *module_group*)
R6(**subtask_ID**, subtask_name, subtask_completion, *task_ID*)

R1(**user_ID**, user_name, user_surname, user_email, user_role)
(user_ID) = {user_ID, user_name, user_surname, user_email, user_role}

R2(**subject_ID**, subject_name)
(subject_ID) = {subject_ID, subject_name}

R3(**module_ID**, module_name, module_code, *subject_ID*)
(module_ID) = {module_ID, modules_name, module_code, subject_ID, ~~subject_name~~}

R4(**module_ID**, **module_year**, **module_term**, module_timetable)
(module_ID, module_year, module_term) = (module_ID, module_year, module_term, module_timetable, ~~modules_name, module_code, subject_ID, subject_name~~)

R5(**task_ID**, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*)
(task_ID) = {task_ID, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, *module_year*, *module_term*, *module_group*, ~~modules_name, module_code, module_timetable, subject_ID, subject_name~~}

R6(**subtask_ID**, subtask_name, subtask_completion, *task_ID*)
(subtask_ID) = {subtask_ID, subtask_name, subtask_completion, *task_ID*, ~~task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, modules_name, module_code, subject_ID, subject_name~~}

## Relations

- user(**user_ID**, user_name, user_surname, user_email, user_role)
- subject(**subject_ID**, subject_name)
- module(**module_ID**, module_name, module_code, *subject_ID*)
- module_timetable(**module_ID**, **module_year**, **module_term**, module_timetable)
- task(**task_ID**, task_name, task_description, task_deadline, task_date_created, task_type, task_importance, task_completion, *module_ID*, *module_year*, *module_term*, *module_group*)
- subtask(**subtask_ID**, subtask_name, subtask_completion, *task_ID*)

![Noodle Database drawio](https://user-images.githubusercontent.com/58662575/174331372-e5538b77-b964-441f-a7d0-0d22642fadc0.svg)

**Comment by djpiper28** [comment]
Users probably need a (salted) password for login.

**Comment by djpiper28** [comment]
Should user roles be many to many?

**Comment by mbeps** [comment]
> Should user roles be many to many?

For our last project, we decided that each user can only have one role. So student, teacher, etc.

**Comment by djpiper28** [comment]
> > Should user roles be many to many?
> 
> For our last project, we decided that each user can only have one role. So student, teacher, etc. 
> 
> 
> > Users probably need a (salted) password for login.
> 
> Some library called NextAuth.js deals with that. It kinda creates a new table in the schema which you can then relate to a user. We don't do authentication manually. I'm not sure if we are still using this library though. 

Surely if there was an English module and a maths module then the teachers for both should only be able to edit their own module. Maybe using roles for this would be a smooth way to do it.

**Comment by mbeps** [comment]
> Surely if there was an English module and a maths module then the teachers for both should only be able to edit their own module. Maybe using roles for this would be a smooth way to do it.

Indeed, this is the reason why we have roles. It's kinda like a way for us to manage privileges. For modifying the module, it wouldn't exactly be great if the teacher assigned to that module; that's because a module can take place in multiple years and it will have different years, we decided to have like a module leader or head of module that would be able to modify the module. For example, a 2017 CS2800 would be separate from a 2018 CS2800, for this reason, they would have independent assignments, timetables, teachers and students. If they were not separate, a teacher from CS2800 (2017) would end up making that assignment for all of CS2800 like 2018, 2019, etc.

**Comment by djpiper28** [comment]
> > Surely if there was an English module and a maths module then the teachers for both should only be able to edit their own module. Maybe using roles for this would be a smooth way to do it.
> 
> Indeed, this is the reason why we have roles. It's kinda like a way for us to manage privileges. For modifying the module, it wouldn't exactly be great if the teacher assigned to that module; that's because a module can take place in multiple years and it will have different years, we decided to have like a module leader or head of module that would be able to modify the module. For example, a 2017 CS2800 would be separate from a 2018 CS2800, for this reason, they would have independent assignments, timetables, teachers and students. If they were not separate, a teacher from CS2800 (2017) would end up making that assignment for all of CS2800 like 2018, 2019, etc. 

Aren't a few link tables missing for that? Module users and; then an owner field on module.

**Comment by mbeps** [comment]
Making a table for the roles would be a great idea actually. This would also allow us to filter types of roles for a specific set of tables, for example, roles for users assigned to each modules (student, teacher and head), roles for users in an assignment (teacher and students). Is this what you were referring too?

**Comment by djpiper28** [comment]
> Making a table for the roles would be a great idea actually. This would also allow us to filter types of roles for a specific set of tables, for example, roles for users assigned to each modules (student, teacher and head), roles for users in an assignment (teacher and students). Is this what you were referring too? 

Similar typically I use bitflag based permissions however that sounds like it would work. Maybe each module user has a role?

**Comment by mbeps** [comment]
> Maybe each module user has a role?

Yeah, I agree. Making the role outside of the user table would be more efficient since a student in 1 module can potentially be something like a TA for another module. However, what would the functional dependency for this be?

`module_ID, module_year, module_term, module_group, user_ID → role`. Something like that?

**Comment by djpiper28** [comment]
> > Maybe each module user has a role?
> 
> Yeah, I agree. Making the role outside of the user table would be more efficient since a student in 1 module can potentially be something like a TA for another module. However, what would the functional dependency for this be?
> 
> `module_ID, module_year, module_term, module_group, user_ID → role`. Something like that?

That doesn't seem normalised maybe module users have a role id which comes from a role table for a module.

**Comment by mbeps** [comment]
Yeah, it's not normalised. I want to know if the functional dependency is correct so that the normalisation is correct. If the FD is wrong, then the normalisation would not make sense with the real world. Do you agree with the FD? If you do, I guess I can normalise it by tomorrow or something unless someone else wants to do it.

**Comment by mbeps** [comment]
@djpiper28 I just spoke to @ixahmedxi and he said that we will not have that many roles anyway and that it's not neccessary to have a many-to-many relationship. Basically, since there is no student in module that can be a TA in another module, there is no point. 
I also wanted to see if adding a new table for roles would make sense; but because the relationship between a user and a role is now one-to-one, it can simply be merged with the users' table which is basically the current layout. 
With this new information, it seems like the database does not require any further modifications.

**Comment by djpiper28** [comment]
In rhul a student in X can be a TA in Y. Take third years TAing 1st/2bd years.

**Comment by djpiper28** [comment]
I think allowing for users to have multiple roles such as the example above is an important feature. Maybe adding to the module-users link table the role works.

**Comment by mbeps** [comment]
> I think allowing for users to have multiple roles such as the example above is an important feature. Maybe adding to the module-users link table the role works.

I also think it's an important feature but it seems like we can add this pretty easily without making major modifications. This is what it's been said
> no let's make it incremental instead of having a database that saves empty values
i don't think we will
our project is for students only and providing them a way to manage their students
studies
