### ISSUE TITLE
add me to contributors list

### ISSUE THREAD

**Issue by ixahmedxi** [ixahmedxi/noodle#145]

**Comment by ixahmedxi** [comment]
@all-contributors please add @ixahmedxi for everything

**Comment by ixahmedxi** [comment]
@all-contributors yes

**Comment by ixahmedxi** [comment]
@all-contributors please add @ixahmedxi for audio, video, code, doc, a11y, bug, blog, business, code, content, data, doc, design, example, eventOrganizing, financial, fundingFinding, idea, maintenance, mentoring, platform, plugin, projectManagement, promotion, question, research, review, security, tool, translation, test, tutorial, talk, userTesting and infra

**Comment by ixahmedxi** [comment]
@all-contributors please add @antoniobfm for doc

**Comment by ixahmedxi** [comment]
@all-contributors please add @nrwl for financial

**Comment by Sp625284** [comment]
Write to update Security in Got hub
Low line shortcut to opening of App additional Features using Git clone Factor using implementation of Lagon Factor means adding repository of method overloading method and multithreading method.


Push a code 
Code is
<Alpha> version 2.0

**Comment by Devesh-N** [comment]
> @all-contributors please add @nrwl for financial

Hello @ixahmedxi Can you please show me what's the current status of this project? I am an open source noob so have no idea on this

**Comment by adhillon192** [comment]
Can you create a pull request for me?

**Comment by Devesh-N** [comment]
@ixahmedxi Can you add me to the contributors list too?
