### ISSUE TITLE
[FEAT] add portuguese (BR) language to this app

### ISSUE THREAD

**Issue by jv26-nascimento** [ixahmedxi/noodle#159]
**Is your feature request related to a problem? Please describe.**
I'm a brazillian student dev, and I'll like so much to have this application in my native language.

**Describe the solution you'd like**
Some as possible, add a translation for the portuguese language.

**Describe alternatives you've considered**
If you need, I'll like to try to help you in this translation, I would like to help with the translation of the project as necessary, as I am fluent in Portuguese

**Additional context**
if it is possible to forward what you want to receive a translation and how should I do it, I would appreciate it

**Comment by ixahmedxi** [comment]
Hey, translations is a planned feature but not for the initial version of the application.
