### ISSUE TITLE
How can I setup Noodle locally?

### ISSUE THREAD

**Issue by nityam01** [ixahmedxi/noodle#160]
I want to try noodle and if possible can contribute.

What commands do I need to setup Noodle properly?

**Comment by Devesh-N** [comment]
Same issue here!

**Comment by Devesh-N** [comment]
I would appreciate some documentation

**Comment by nityam01** [comment]
Hey, I am able to set up Noodle locally. 
Will make a Pull request

**Comment by Devesh-N** [comment]
> Hey, I figured out and was able to set up Noodle locally. Will make a Pull request.

@nityam01 Me too just check my issue

**Comment by nityam01** [comment]
#163

**Comment by Devesh-N** [comment]
> #163

@nityam01 I made Dockerfile Now but I don;t know how to commit

**Comment by Devesh-N** [comment]
Update I just did pull request

**Comment by Devesh-N** [comment]
@nityam01

**Comment by nityam01** [comment]
If you want to make a pull request... you can follow these steps
1. Make a new branch i.e. docker-setup and checkout
2. Make changes and push to the docker-setup branch
3. Now you can make a pull request from your GitHub ( a button compare & pull request )

**Comment by Devesh-N** [comment]
> If you want to make a pull request... you can follow these steps
> 
> 1. Make a new branch i.e. docker-setup and checkout
> 2. Make changes and push to the docker-setup branch
> 3. Now you can make a pull request from your GitHub ( a button compare & pull request )

@nityam01 I did the pull request. You can add in readme that to execute it you need to run this in root project folder
docker build .
docker images
`Copy the image id`
docker run -dit -p 3000:3000 `image id`
After it's done go to localhost:3000

**Comment by Devesh-N** [comment]
Hope you will be adding these changes @nityam01

**Comment by nityam01** [comment]
Sure, once @ixahmedxi will approve your request, I will add these changes

**Comment by Devesh-N** [comment]
> Sure, once @ixahmedxi will approve your request, I will add these changes

@nityam01 Okay

**Comment by AI-ALALEI** [comment]
Can I join?

**Comment by Devesh-N** [comment]
> Can I join?

@AI-ALALEI Sure

**Comment by MUK-Dev** [comment]
Hello, I also want to contribute to this project. Can you guys guide me a little?

**Comment by Johnmiicheal** [comment]
I didn't use Docker, but I got it to run locally, with ```npm run dev``` but all I can access is the landing page

**Comment by Johnmiicheal** [comment]
> I didn't use Docker, but I got it to run locally, with `npm run dev` but all I can access is the landing page

@ixahmedxi Please can you point me in the right direction

**Comment by ntananh** [comment]
When I run `pnpm start dev`, it throw an error:
```
> @noodle/vitest@0.1.0 build /Users/unhomie/workspace/js/noodle/packages/config/vitest
> tsc

index.ts(10,13): error TS2322: Type 'Plugin_2' is not assignable to type 'PluginOption'.
......
```

Does anyone face this issue?

**Comment by Devesh-N** [comment]
> When I run `pnpm start dev`, it's throw an error:
> 
> ```
> > @noodle/vitest@0.1.0 build /Users/unhomie/workspace/js/noodle/packages/config/vitest
> > tsc
> 
> index.ts(10,13): error TS2322: Type 'Plugin_2' is not assignable to type 'PluginOption'.
> ......
> ```
> 
> Does anyone face with this issue?

@ntananh Please use my Dockerfile along with instructions and no error will be there

**Comment by Devesh-N** [comment]
> I didn't use Docker, but I got it to run locally, with `npm run dev` but all I can access is the landing page

@Johnmiicheal That's because there is only landing page 🤣This is still in development

**Comment by ixahmedxi** [comment]
I really appreciate you guys' interest in contributing to this project and will definitely allow this to happen. Just give me time to get the landing page and waiting list out so that I can then create a proper CONTRIBUTING.md file explaining everything you need to run this project locally. Just for your own pleasure the project uses:

- Node v18.15.0
- Pnpm v8.6.x
- Volta

If you have all these, you then go into the project, run `pnpm install` then `pnpm build:pkgs` and then `pnpm dev`

note that there is a `.env.example` file because you need some environment variables to do with the database, authentication...etc that you might need to copy into a `.env` file and populate that with your unique values.

If you get random prisma errors, do `pnpm nx db:generate db`

**Comment by Devesh-N** [comment]
> I really appreciate you guys' interest in contributing to this project and will definitely allow this to happen. Just give me time to get the landing page and waiting list out so that I can then create a proper CONTRIBUTING.md file explaining everything you need to run this project locally. Just for your own pleasure the project uses:
> 
> * Node v18.15.0
> * Pnpm v8.6.x
> * Volta
> 
> If you have all these, you then go into the project, run `pnpm install` then `pnpm build:pkgs` and then `pnpm dev`
> 
> note that there is a `.env.example` file because you need some environment variables to do with the database, authentication...etc that you might need to copy into a `.env` file and populate that with your unique values.
> 
> If you get random prisma errors, do `pnpm nx db:generate db`

Thanks, @ixahmedxi can I know which language do we have to contribute on? I know basic Python and very very basic rust

**Comment by ixahmedxi** [comment]
This is a full typescript project

**Comment by Johnmiicheal** [comment]
Thanks @ixahmedxi , can't wait to start contributing to this project✌✨

**Comment by Devesh-N** [comment]
> This is a full typescript project

@ixahmedxi Is there any DevOps requirement?

**Comment by nkilm** [comment]
It would be nice to have the dev environment ready with simple command, we can make use of either `docker-compose` or custom scripts. 

For reference, you can checkout [cal.com](https://github.com/calcom/cal.com). Only one command - `yarn dx` is more than enough to setup dev env. We can try to make something similar.

**Comment by Devesh-N** [comment]
> It would be nice to have the dev environment ready with simple command, we can make use of either `docker-compose` or custom scripts.
> 
> For reference, you can checkout [cal.com](https://github.com/calcom/cal.com). Only one command - `yarn dx` is more than enough to setup dev env. We can try to make something similar.

@nkilm I already made dockerfile. You can now do one line setup on environment

**Comment by nkilm** [comment]
@Devesh-N Yes

**Comment by Devesh-N** [comment]
> @Devesh-N Yes

@nkilm Did it work? I think it should be there in the PR section
