### ISSUE TITLE
How to install (Docker + Regular) [SOLVED]

### ISSUE THREAD

**Issue by Devesh-N** [ixahmedxi/noodle#162]
Hello, sorry for being a pain but I have no idea how I can install and access Noodle. I am a noob in javascript but I have node version 18 installed. How can I install this @ixahmedxi ? Help appreciated...

**Comment by Devesh-N** [comment]
Also, @ixahmedxi I can help in Dockerizing this app as I am a DevOps intern. But I can't Dockerize without clear and concise documentation. But AI can surely help me to a certain extent in understanding this project. I also have experience with Jenkins CI/CD but not GitHub actions

**Comment by sumyno7** [comment]
I saw in the description that noodle is not ready for use yet.
btw i am also a js noob and want to contribute. I am new in this open source rabbit hole and just started to use github.
Infact this is my first github comment so please forgive me if i am terribly wrong.

**Comment by Devesh-N** [comment]
> I saw in the description that noodle is not ready for use yet. btw i am also a js noob and want to contribute. I am new in this open source rabbit hole and just started to use github. Infact this is my first github comment so please forgive me if i am terribly wrong.

No probs @sumyno7

**Comment by Devesh-N** [comment]
@sumyno7 It is in fact not ready to use. I thought that it was. Here's what I did to install it (Also, I used AI to generate docs on using this pasting here)
Based on the information provided, this project seems to use pnpm as its package manager. Here are the general steps to install a project like this:

Ensure that you have Node.js installed on your machine. The project specifies that it requires Node.js version 18.15.0 or later. You can download Node.js from the official website.
Install pnpm globally on your machine. You can do this by running npm install -g pnpm in your terminal.
Clone the project repository to your local machine.
Navigate to the project directory in your terminal.
Run pnpm install to install the project dependencies.
Please note that these are general instructions and the installation steps may vary based on the project's specific requirements. Always refer to the project's README or other documentation for the most accurate information.


To run the project, you can use the start script defined in the package.json file. This script is set to run pnpm nx run-many -t start --parallel=99.

You can execute this script by running the following command in your terminal:

pnpm start
This command will start the project using the configuration defined in the start script.

Here is the start script from the package.json file:


3
"start": "pnpm nx run-many -t start --parallel=99"
Please note that the actual command to run the project may vary based on the specific requirements of the project. Always refer to the project's README or other documentation for the most accurate information.

**Comment by Devesh-N** [comment]
@sumyno7  Doing this I get the regular interface which is right over here: https://noodle.run/

**Comment by sumyno7** [comment]
Thanks a ton Devesh!

**Comment by Devesh-N** [comment]
@sumyno7 I have made Dockerfile also I will be doing Pull request soon

**Comment by sumyno7** [comment]
ok cool , go ahead.

**Comment by Devesh-N** [comment]
@sumyno7 Done, you can check it in the Pull Request section. You can use it too

**Comment by P-4-PRATYUSH-RANJAN** [comment]
from your conversation i learned  a lot , so thank you guys @sumyno7 and @Devesh-N

**Comment by Devesh-N** [comment]
Thanks @P-4-PRATYUSH-RANJAN You can learn even more by checking out my dockerfile in pull request section

**Comment by Devesh-N** [comment]
@P-4-PRATYUSH-RANJAN You can endorse me on LinkedIn also: https://www.linkedin.com/in/contact-devesh-nair/

**Comment by ixahmedxi** [comment]
contributing guidelines will come shortly

**Comment by Devesh-N** [comment]
> contributing guidelines will come shortly

Okay @ixahmedxi ping me when they do come out
