### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by Otsira** [ixahmedxi/noodle#173]
**Is your feature request related to a problem? Please describe.**
A plugging system for extending the functionality and customization of the platform

**Describe the solution you'd like**
It would be great to be able to add plugins like one drive or nextcloud sync without having to add them directly to the project or waiting for the feature release. It can be tricky, at least with UI plugins, but it can be done. 

**Describe alternatives you've considered**

**Additional context**
I want to have everything stored on my NAS as markdown or atleast HTML, this could make it so anyone can implement that feature with out the burden on the main devs

**Comment by ixahmedxi** [comment]
Hello, with the direction the project is heading, an initial version will be a lot more individual. I would love to have this sort of a feature definitely but it will probably need to be revised and planned way ahead in time and not currently.
