### ISSUE TITLE
[FEAT] Roadmap

### ISSUE THREAD

**Issue by kevenleone** [ixahmedxi/noodle#193]
**Is your feature request related to a problem? Please describe.**
Is there a roadmap / board, where we can find the future tasks to be done?

**Describe the solution you'd like**
It could be a board or something similar using Github

**Describe alternatives you've considered**

**Additional context**
This is helpful to everyone that is willing to contribute somehow with the project

**Comment by NikxDa** [comment]
Can I just pile onto this and ask what the current state of this project is at all? It has 5.8k stars yet I don't see it being anything apart from a fancy mockup screenshot.

**Comment by kevenleone** [comment]
Yeah... Agree with you.

**Comment by sasmlange** [comment]
According to the Noodle FAQ:

> We are working hard to get the first initial version of Noodle out as soon as possible, that might be hopefully during
September time that aligns with the new school year.

**Comment by ixahmedxi** [comment]
Noodle has gained a lot of traction at the start of it's development and hence why there isn't much out there as of now. I'm working hard on getting something out as soon as possible.

As for contributions, it's impossible for me to prioritise managing contributions as opposed to getting the project on good solid foundations, after that I will be more than happy to accept many contributions, provide guidance and let the community make noodle better. Thank you for the interest I truly appreciate it!
