### ISSUE TITLE
[BUG] - Typo in FAQ

### ISSUE THREAD

**Issue by buhama** [ixahmedxi/noodle#203]
**Describe the bug**
- Survery should be survey

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="792" alt="image" src="https://github.com/ixahmedxi/noodle/assets/84474317/d8843fc8-85ab-4ba3-9248-bac5af297ed3">

**Information (please complete the following information):**

- Node version [e.g. 18.15.0]
- Pnpm version [e.g. 8.6.6]

**Additional context**

**Comment by Ayothegod** [comment]
can I work on this?
