### ISSUE TITLE
[BUG] Typo on website to join waiting list

### ISSUE THREAD

**Issue by mathislindner** [ixahmedxi/noodle#206]
**Describe the bug**
Typo in the paragraph talking about joining the waiting list. 

**To Reproduce**
https://noodle.run/waitlist

**Expected behavior**
Should say getting and not geting. 

**Screenshots**
![Screenshot_System_UI_20230709-130534__01.png](https://github.com/ixahmedxi/noodle/assets/63106141/bace28fc-c2e8-4434-850d-9b7e6dcad8fd)

**Information (please complete the following information):**

- Node version [e.g. 18.15.0]
- Pnpm version [e.g. 8.6.6]

**Comment by swapn652** [comment]
Can I work on this?

**Comment by ixahmedxi** [comment]
Fixed
