### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by Ayothegod** [ixahmedxi/noodle#209]
**Is your feature request related to a problem? Please describe.**
The contributing.md file is empty

**Describe the solution you'd like**
As an open-source developer myself, I find this project exciting. hence I want to create the contribution file to guide developers interested in volunteering for this project

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by darigovresearch** [comment]
Hi @Ayothegod thanks for raising this, can you rename the title of your issue so people can understand what the issue is without needing to open the issue?

Changing it to something like  `[FEAT] Add content to contribution.md` would be better

**Comment by ixahmedxi** [comment]
This is intentional because we are not in position to accept big contributions just yet.
