### ISSUE TITLE
[BUG] Add link to license in readme

### ISSUE THREAD

**Issue by darigovresearch** [ixahmedxi/noodle#210]
**Describe the bug**
No link in readme

**To Reproduce**
Go to readme

**Expected behavior**
Thought it may be helpful/convenient to have a link to the license in the readme

**Screenshots**
na.

**Python package version**
na

**Additional context**
na

**Comment by ixahmedxi** [comment]
The license is visible on the github repo, on the right side, I wouldn't want to populate the readme with so much stuff
