### ISSUE TITLE
[BUG] Contributor Badge number not correct

### ISSUE THREAD

**Issue by darigovresearch** [ixahmedxi/noodle#211]
**Describe the bug**
Contributor badge number not matching number of contributors to repo

**To Reproduce**
Go to readme

**Expected behavior**
Contributor badge number should match number of contributors to repo

**Screenshots**
![image](https://github.com/ixahmedxi/noodle/assets/30328618/8c41190a-0f28-4587-b3e4-e0d2dbccee95)

**Information (please complete the following information):**
NA

**Additional context**
NA

**Comment by shaikahmadnawaz** [comment]
Can I change this?

**Comment by xhayper** [comment]
I am pretty sure this is intended because in the [project's all-contributors configuration file](https://github.com/ixahmedxi/noodle/blob/0e80e7dbc589d054fe50a51a3b47557341ee0866/.all-contributorsrc), they specify that contributor are not added when they commit, but rather are added manually.
