### ISSUE TITLE
[BUG] Missing contact method in code of conduct

### ISSUE THREAD

**Issue by darigovresearch** [ixahmedxi/noodle#212]
**Describe the bug**
There is no contact method yet listed in the code of conduct - https://github.com/ixahmedxi/noodle/blob/main/CODE_OF_CONDUCT.md#enforcement

**To Reproduce**
Go here https://github.com/ixahmedxi/noodle/blob/main/CODE_OF_CONDUCT.md#enforcement

**Expected behavior**
Have an email address so someone can reach out if needed

**Screenshots**
![image](https://github.com/ixahmedxi/noodle/assets/30328618/999d94a8-d39f-4130-8172-be48d54ab32d)

**Information (please complete the following information):**
NA
**Additional context**
NA

**Comment by shaikahmadnawaz** [comment]
Mention the details of a contact, and I will add them.

**Comment by ixahmedxi** [comment]
Fixed
