### ISSUE TITLE
Get the typography components implemented & into the design system

### ISSUE THREAD

**Issue by ixahmedxi** [ixahmedxi/noodle#215]
As a first step towards building our design system, we should implement the various typography styles that we will have across the website in terms of components. For example H1, H2, H3, H4 and Paragraph components.

The design system on figma elaborates the different typography styles and it should be done as components 1:1 to the design.

**Comment by Ritesh9876** [comment]
Hello @ixahmedxi, Can I work on this issue. I am new to open source contribution and I would like to contribute to this project.
