### ISSUE TITLE
[FEAT]: setup t3-env in the monorepo

### ISSUE THREAD

**Issue by ixahmedxi** [ixahmedxi/noodle#245]
https://github.com/t3-oss/t3-env is a package that gives you the ability to have typesafe, runtime-checked environment variables, this means that if an environment variable is not defined, the build errors out instead of discovering it in production like I just did with my Redis environment variables name change.

I would like to setup this package for the `web` app, `db` package and `auth` package so that we are sure we have the required environment variables whenever we build the application.

**Comment by ixahmedxi** [comment]
Assigned to @bobby29831

**Comment by bobooski** [comment]
Going on vacation for around a week... if someone can get this done before I get back, it's fair game for them, otherwise I'll work on it when I get back.

**Comment by tristancamejo** [comment]
I can have it done by tonight, just at work

**Comment by bobooski** [comment]
Cool, have at it 👍
