### ISSUE TITLE
Rate limiting, deployment, and architectural concerns

### ISSUE THREAD

**Issue by djpiper28** [ixahmedxi/noodle#246]
I have some concerns related to the rate limiting and deployment which are caused by the architecture.

---

Rate limiting via software with Redis seems sketchy. The reason I say this is twofold:
 - potential for DoS attacks to not be well mitigated with the rate limit in JS
 - cloud native solutions (or an nginx web server for local deployment) seems more suited for providing the desired protection

## Potential Mitigations

 - Cloud native gateway with rate limiting and caching, i.e: AWS's route 53 but for Vercel.
 - Cloudflare proxying to help mitigate bots
 - Captcha on open registration forms or similar verification methods

## Relation to Other Issues

 - Dockerisation & Self Hosting: dockerfiles (using docker-compose) for the project

**Comment by ixahmedxi** [comment]
While I appreciate your concern, upstash rate limiting works on nextjs middleware, and nextjs middleware if you know runs before any request and routing is matched. The case of rate limiting is the exact way upstash recommends it and many companies and projects use the same method.

If you have any concerns with the way upstash does and recommends rate limiting, I would suggest filing an issue there instead.

As for the dockerization for self hosting, i have already mentioned its not in my current plans.

**Comment by ixahmedxi** [comment]
cc https://upstash.com/blog/edge-rate-limiting
