### ISSUE TITLE
[FEAT] E2E Test using Page-Object-Model Pattern

### ISSUE THREAD

**Issue by depapp** [ixahmedxi/noodle#252]
**Describe the solution you'd like**
implement Page-Object-Model pattern into this project

**Additional context**
reference: 
- https://martinfowler.com/bliki/PageObject.html
- https://playwright.dev/docs/pom

**Comment by ixahmedxi** [comment]
Right now I'm very focused on shipping something initially, when this happens I will be adding forms of testing to the project as needed. Discussions on the best testing strategy for the project will take place then. Thank you a lot for the interest in contributing to this project, I really appreciate it and I look forward to providing a ground where people can contribute freely to the success of this project <3
